-- Add missing columns to products table
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS unit TEXT DEFAULT 'قطعة',
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS item_number TEXT,
ADD COLUMN IF NOT EXISTS opening_stock INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS purchases INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS issues INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS inventory_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS current_stock INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS difference INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS average_price NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS current_stock_value NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS issues_value NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS min_stock_limit INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS last_activity TIMESTAMP WITH TIME ZONE;
